version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: task-api
    environment:
      DATABASE_URL: "postgresql://user:password1@postgres:5432/test?schema=public"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend
    command: >
      sh -c "
        echo 'Aspetto 20 secondi per PostgreSQL...' &&
        sleep 20 &&  # Ho aumentato il tempo di attesa per PostgreSQL
        until nc -z postgres 5432; do echo 'Attendo PostgreSQL...'; sleep 1; done && # Verifica che il DB sia pronto
        npx prisma generate &&
        npx prisma migrate dev --name init &&
        npx prisma migrate deploy &&
        node server.js # Esegui il server solo dopo le migrazioni
      "

volumes:
  postgres_data:

networks:
  backend:
